### ISSUE TITLE
Safe won't run on Mojave

### ISSUE THREAD

**Issue by mikerj1** [safeapp/safe#103]
MacOS 10.14.5 - this is the first time I've tried Safe.  After extraction, the app won't start.  Trying to start the command line gives the following:

$ open /Applications/Safe.app/
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Safe.app

or if just executing:

$ /Applications/Safe.app/Contents/MacOS/Safe
Killed: 9

Googling lead me to install upx and decompress, which then allowed the app to run.  However, after creating a new safe, I get an "unknown error" when it attempts to mount.  Clicking Report Bug results in "Submission failed :( Reload to try again."

**Comment by rianhunter** [comment]
hey, thanks for the bug report. unfortunately safe is currently unmaintained. i suggest seeking out an alternative solution. installing encfs via homebrew may be a suitable replacement.
