### ISSUE TITLE
app/report_exception fails

### ISSUE THREAD

**Issue by alysdexia** [safeapp/safe#104]
tried to submit http://www.getsafe.org/app/report_exception?where=ExceptionLocation%3A%3ACREATE&version=1.4&target_platform=win&platform=windows-x64-6.2.9200&arch=i386&value_sizes=1%2C2%2C4%2C4%2C8%2C4%2C4%2C8%2C12&what=FS_ERROR_DOES_NOT_EXIST&exception_type=std%3A%3Asystem_error&offset_stack_trace=0x2652f%2C0xdb871%2C0x5041%2C0%2C0%2C0&

but got "Submission failed :( Reload to try again."

**Comment by rianhunter** [comment]
Thanks, your report was accepted here.
