### ISSUE TITLE
Project Status / Version 2.0 Milestones?

### ISSUE THREAD

**Issue by CarliJoy** [safeapp/safe#106]
@rianhunter what is the current state of the project?  2016 you posted:

> Project isn't abandoned, it's being rewritten. Wish I had the time to focus on support for old versions :(

_Originally posted by @rianhunter in https://github.com/safeapp/safe/issues/80#issuecomment-239690900_

But there was no new release or update since this.
As you seem to be the only Developer of the App, is it safe to say, you didn't have time to finish the second version? 
Any outlook if/when you would be able to finish a second version?

Best regards,

Carli*

**Comment by rianhunter** [comment]
Hi Carli, the project is effectively abandoned at this point.
