### ISSUE TITLE
No uninstall entry 

### ISSUE THREAD

**Issue by NostromosGamer** [safeapp/safe#59]
Why is there no uninstall entry in the control panel for SAFE?  How do I uninstall the program?

**Comment by RogerThiede** [comment]
There is no installer; just a portable executable to execute or delete.

**Comment by JerryLerman** [comment]
Add me to the list of people who wantto know how to uninstall.

**Comment by AppliedEllipsis** [comment]
I think people are asking about the system level changes made:
It's really a matter of reversing the different changes you want and deleting a link.
http://www.getsafe.org/about#system_changes_more_info
make sure the webdav mount is not mounted (in explorer right click->disconnect)
fsutil behavior set EncryptPagingFile 0
powercfg /hibernate on
del C:\Windows\ServiceProfiles\LocalService\AppData\Local\Temp\TfsSTore\Tfs_DAV
(navigate the structure or run explorer/cmd prompt as admin, points to \\evice\SafeRamDisk)
Go to device manager and right click and uninstall the Safe RAMDisk entries.
you may need to reverse the last 2 steps.

**Comment by rianhunter** [comment]
Yes there is currently no uninstall entry, Safe is distributed as a portable executable. There are no plans to change this in the foreseeable future. I am friendly to PRs on this though.

To undo any system changes Safe may have made, execute the commands in AppliedEllipsis's comment. Only do this if you know what you're doing. If you don't know how to run those commands, then ignore it.
