### ISSUE TITLE
Al Capitan support

### ISSUE THREAD

**Issue by johnwchadwick** [safeapp/safe#66]
Installing this in Mac OS X 10.11 prerelease works, and mounting "succeeds" (it properly checks password and reports success when entered correctly,) but the actual mounting does not work. It's not listed in `mount` nor are any files visible. I have not determined what the issue is, but I imagine it might be related to FUSE. I have OSXFuse installed and seemingly working, as there is a preview with Al Capitan support.

**Comment by rianhunter** [comment]
Safe doesn't use FUSE. I haven't run into this problem. Reminder that Safe requires FileVault encryption to be enabled. Is this still an issue?

**Comment by johnwchadwick** [comment]
My bad, I have since realized that it uses WebDAV but I never figured out that FileVault was required. I did since encrypt with FileVault, and now it works fine. Sorry.

**Comment by rianhunter** [comment]
FileVault is a silent requirement, so it's more my bad than your bad :) I'm glad it's been working since and thanks for using Safe! Version 2.0 will be much better :)
