### ISSUE TITLE
OS X 10.10: Mounted volumes can never be unmounted

### ISSUE THREAD

**Issue by IlyaSemenov** [safeapp/safe#69]
On OS X Yosemite 10.10.5, once a safe volume is mounted, it can never be unmounted.
![Screen shot](https://cloud.githubusercontent.com/assets/128121/9683093/355b80d4-5326-11e5-8e44-b42ea4b64ee1.png)

`lsof` finds the `mds` process (Spotlight indexer) using the folder:

    sh-3.2# lsof|grep -i safe|grep -i ramd
    mds         52            root   18r      DIR               1,5        238       2 /Volumes/.safe-ramdisk-mount-ydkNld

Manually disabling Spotlight with `mdutil -Ed /Volumes/.safe*` doesn't help, although `mdutil -as` reports thats indexing and searching become disabled after that.

Creating a file named .metadata_never_index inside the mounted folder doesn't help either.

**Comment by IlyaSemenov** [comment]
Note: enabling FileVault magically fixed everything.

**Comment by rianhunter** [comment]
Hi, Sorry about that. On Mac OS X >= 10.9, Safe silently requires filevault. This is known. Safe 2.0 will not have this requirement.
