### ISSUE TITLE
PDF's

### ISSUE THREAD

**Issue by jlhooton** [safeapp/safe#83]
You've developed a super program that I use regularly. I have great respect for folks like you who put your time into improving our computing lives, so this is said with thanks and appreciation.

I've run into some strange behavior you might want to know about.

If I copy or move a pdf from any folder on my computer to an open Safe drive and then try to read it on Windows 10 using Foxit PDF reader  I get:
 
"The URL you have provided could not be reached.  Please verify that the URL is correct and that the network location is reachable."

If I try to open the PDF using Edge I get "Hmm, we can't reach this page."

I can copy or move the PDF and it makes no difference and I can  copy or move it to any other folder on my Win 10 system and the pdf will open with Edge or with Foxit.  I also tried this on Linux using Cryptkeeper and moving the pdf to the encrypted folder and opening it works fine.

I also tried to copy or move a pdf that I scanned in from a printed document to the Safe folder and the same error message comes up about the URL even though this wasn't a document downloaded from the web.  As soon as a pdf touches the open Safe folder and I try to open it on Win 10 with Foxit or with Edge, there's an error message.  

Interestingly, If I choose to open the pdf using Chrome in the Safe Folder, it will do so just fine.  So something isn't playing nicely between Safe and Foxit or Edge.

Again, this is sent with thanks and appreciation and no expectations that you do a thing but if it helps, I feel like I'm contributing a bit.  best Jim

**Comment by rianhunter** [comment]
Hi Jim,

Thanks for the love man. Means a lot. Safe was a good 10 months of my life.

As for this problem, does the issue persist with the file if you drag it out of safe into a normal folder and then try to open it from a normal folder?

If the answer is "no" then I would have to guess there is some quirk in the Windows interpretation of WebDAV that we're not handling correctly or that Foxit/Edge don't handle WebDAV folders in general.

Safe 2.0 no longer uses WebDAV, instead it uses SMB. This is a higher quality and more stable solution, it will just take more time to release. For now you'll have to deal with this issue until Safe 2.0 is released later this year. Sorry.

Rian

**Comment by jlhooton** [comment]
Your welcome Rian.  No the issue doesn't persist if I drag or copy the file
back from the Safe folder to my desktop.  Windows Security warms me that
the file might be malicious or a threat but it opens fine.  No problem with
using Chrome to open the PDF now that I know and we'll wait for Safe 2.0.
Thanks again.  Jim

**Comment by jlhooton** [comment]
I'm closing this and leaving it in your capable hands, best Jim

**Comment by maximbaz** [comment]
Hey @rianhunter, just wondering how is it going with Safe 2.0? Is there any beta version to try out? 
I'm asking because I couldn't find any mention of this on the website, twitter or here on github (including the source code).

**Comment by rianhunter** [comment]
There is no public beta. I have a private version that I'm personally using but still needs lots of work before it can be released to the public.
