### ISSUE TITLE
How to cleanly uninstall on Mac OS X

### ISSUE THREAD

**Issue by nikolay** [safeapp/safe#84]
As this hasn't been working for a while, I wonder how to uninstall it.

**Comment by rianhunter** [comment]
Just drag it to the trash.

**Comment by nikolay** [comment]
@rianhunter *cleanly* as dragging to Trash it leaves junk behind!

**Comment by rianhunter** [comment]
Safe installs nothing extra. All files are contained within the 
application package. What junk are you referring to?
