### ISSUE TITLE
[Solved] Bug: Error Mounting Safe

### ISSUE THREAD

**Issue by jansuz** [safeapp/safe#90]
I'm unable to post this, I hope this helps...

Steps to reproduce:
* select mounting path (from sync'd OwnCloud)
  = C:\Users\example\ownCloud\Shared\Networks
* Enter password
* Press enter

This works for other Windows 10 operators using safe 1.4.

http://www.getsafe.org/app/report_exception?where=ExceptionLocation%3A%3AMOUNT&version=1.4&target_platform=win&platform=windows-x64-6.2.9200&arch=i386&value_sizes=1%2C2%2C4%2C4%2C8%2C4%2C4%2C8%2C12&what=net%20failed&exception_type=std%3A%3Aruntime_error&offset_stack_trace=0xdceff%2C0xf5901%2C0x5041%2C0%2C0%2C0&

Jol.

**Comment by jansuz** [comment]
Further:
* Have disabled hibernation as recommended.
* Have encrypted paging file as recommended.
* Have installed WebDAV(?) RAM drive as recommended.

Jol.

**Comment by rianhunter** [comment]
Thanks for the report.

Currently don't have enough time to debug this. It seems like an issue with your machine specifically.

I can give you a hint. It has to do with the "net" command in cmd. For some reason, it won't allow you to mount a webdav drive. Try mounting other webdav services with the "net" command and you mind find the issue.

**Comment by jansuz** [comment]
Thank you for the pointer. I've rechecked my running service(s) and have found...

If you experience any issues mounting (with Safe) the vault, ensure that you have the these two services running.
* Web Management
* WebClient

REF: https://en.wikipedia.org/wiki/WebDAV#Microsoft_Windows

Jol.
